version: '3'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "18080:80"
    depends_on:
      - app
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./public/index.php:/var/www/html
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 19000:9000
    depends_on:
      - db
    volumes:
      - ../laravel-app/:/var/www/html/laravel-app
  db:
    container_name: db
    image: postgres:12.2
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'test_db'
    ports:
      - 15432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./docker/db/sql:/docker-entrypoint-initdb.d

# https://qiita.com/ko-da-k/items/47b96883144a5bf1cb1e
volumes:
  db:
    external: true
